{% set name = "mosaicmpi" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58089d9ff51c2dbdfea1f0d8ac37ea7f20c0372ba19ee6aa965de1f754c836b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mosaicmpi = mosaicmpi.cli:cli

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - pip
  run:
    - python >=3.9
    - anndata >=0.8.0
    - pandas
    - numpy
    - scipy >=1.9.0
    - matplotlib-base
    - upsetplot
    - tomli
    - tomli-w
    - distinctipy
    - click
    - pygraphviz
    - python-igraph
    - pyyaml
    - scikit-learn
    - scanpy
    - fastcluster
    - seaborn
    - statsmodels
    - networkx
    - tqdm

test:
  imports:
    - mosaicmpi
  commands:
    - pip list
  requires:
    - pip

about:
  home: https://github.com/MorrissyLab/mosaicMPI
  summary: 'mosaicMPI: mosaic multi-resolution program integration'
  description: >
    mosaicMPI is a Python package enabling mosaic integration of bulk, single-cell, and spatial expression data through program-level integration. Programs are first discovered using consensus non-negative matrix factorization and then integrated using a flexible network-based approach to group similar programs together
    across resolutions and datasets. Program communities are then interpreted using sample/cell metadata and classical gene set analyses. Integrative program communities enable metadata transfer across datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - verheytb
