{% set name = "mosaicmpi" %}
{% set version = "2.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12b2243f712d63945abd0b08550fb89d0e9b5c511069058261a56a9939375714
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mosaicmpi = mosaicmpi.cli:cli

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - pip
  run:
    - anndata
    - click
    - distinctipy
    - fastcluster
    - matplotlib-base
    - networkx
    - numpy
    - pandas
    - pygam
    - pygraphviz
    - python >=3.9
    - python-igraph
    - pyyaml
    - requests
    - scikit-learn
    - scipy
    - seaborn
    - statsmodels
    - tqdm
    - tomli
    - tomli-w
    - upsetplot

test:
  imports:
    - mosaicmpi
  commands:
    - pip list
  requires:
    - pip

about:
  home: https://github.com/MorrissyLab/mosaicMPI
  summary: 'mosaicMPI: mosaic multi-resolution program integration'
  description: >
    mosaicMPI is a Python package enabling mosaic integration of bulk, single-cell, and spatial expression data through program-level integration. Programs are first discovered using consensus non-negative matrix factorization and then integrated using a flexible network-based approach to group similar programs together
    across resolutions and datasets. Program communities are then interpreted using sample/cell metadata and classical gene set analyses. Integrative program communities enable metadata transfer across datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SeanNesdoly
    - verheytb
